2025-03-08 22:15:41,595 INFO    MainThread:14240 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-08 22:15:41,595 INFO    MainThread:14240 [wandb_setup.py:_flush():67] Configure stats pid to 14240
2025-03-08 22:15:41,596 INFO    MainThread:14240 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Ashutosh Patidar\.config\wandb\settings
2025-03-08 22:15:41,596 INFO    MainThread:14240 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Ashutosh Patidar\OneDrive\Documents\GitHub\Assignment_1_Deep_Learning\wandb\settings
2025-03-08 22:15:41,596 INFO    MainThread:14240 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-08 22:15:41,596 INFO    MainThread:14240 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\Ashutosh Patidar\OneDrive\Documents\GitHub\Assignment_1_Deep_Learning\wandb\run-20250308_221541-0a6ngqkx\logs\debug.log
2025-03-08 22:15:41,597 INFO    MainThread:14240 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\Ashutosh Patidar\OneDrive\Documents\GitHub\Assignment_1_Deep_Learning\wandb\run-20250308_221541-0a6ngqkx\logs\debug-internal.log
2025-03-08 22:15:41,597 INFO    MainThread:14240 [wandb_init.py:init():761] calling init triggers
2025-03-08 22:15:41,597 INFO    MainThread:14240 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'Learning_rate': 0.001, 'epochs': 50, 'batch_size': 32, 'layer_size': [784, 128, 64, 10], 'optimizer': 'RMS_Prop', 'beta_1': 0.9, 'beta_2': 0.999, 'loss_function': 'mean_squared', '_wandb': {}}
2025-03-08 22:15:41,597 INFO    MainThread:14240 [wandb_init.py:init():784] starting backend
2025-03-08 22:15:41,597 INFO    MainThread:14240 [wandb_init.py:init():788] sending inform_init request
2025-03-08 22:15:41,676 INFO    MainThread:14240 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-08 22:15:41,678 INFO    MainThread:14240 [wandb_init.py:init():803] backend started and connected
2025-03-08 22:15:41,681 INFO    MainThread:14240 [wandb_init.py:init():896] updated telemetry
2025-03-08 22:15:41,767 INFO    MainThread:14240 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-08 22:15:42,291 INFO    MainThread:14240 [wandb_init.py:init():995] starting run threads in backend
2025-03-08 22:15:52,374 INFO    MainThread:14240 [wandb_run.py:_console_start():2377] atexit reg
2025-03-08 22:15:52,374 INFO    MainThread:14240 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-08 22:15:52,374 INFO    MainThread:14240 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-08 22:15:52,375 INFO    MainThread:14240 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-08 22:15:52,377 INFO    MainThread:14240 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-08 22:15:52,392 WARNING MsgRouterThr:14240 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\Ashutosh Patidar\AppData\Roaming\Python\Python312\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ashutosh Patidar\AppData\Roaming\Python\Python312\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ashutosh Patidar\AppData\Roaming\Python\Python312\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ashutosh Patidar\AppData\Roaming\Python\Python312\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ashutosh Patidar\AppData\Roaming\Python\Python312\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-08 22:15:52,442 INFO    MsgRouterThr:14240 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
